// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCDw4Fh6dPmNt7AYPJy25vWJImuhrKWqI',
    appId: '1:71104364512:web:55e8dc9c69a5a3069df585',
    messagingSenderId: '71104364512',
    projectId: 'flutter-cloud-computing-tasks',
    authDomain: 'flutter-cloud-computing-tasks.firebaseapp.com',
    databaseURL: 'https://flutter-cloud-computing-tasks-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-computing-tasks.firebasestorage.app',
    measurementId: 'G-QTGTQP26L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkW_yv5wl4IIeCJDwA3Mwkw0P-V8KAdKw',
    appId: '1:71104364512:android:a8110bd296e7a8999df585',
    messagingSenderId: '71104364512',
    projectId: 'flutter-cloud-computing-tasks',
    databaseURL: 'https://flutter-cloud-computing-tasks-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-computing-tasks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLpD3VZaZa2_paC4JebQ-ci93iAqrgXrs',
    appId: '1:71104364512:ios:76f34c7dce4aa6389df585',
    messagingSenderId: '71104364512',
    projectId: 'flutter-cloud-computing-tasks',
    databaseURL: 'https://flutter-cloud-computing-tasks-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-computing-tasks.firebasestorage.app',
    iosBundleId: 'com.example.ccSa1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLpD3VZaZa2_paC4JebQ-ci93iAqrgXrs',
    appId: '1:71104364512:ios:76f34c7dce4aa6389df585',
    messagingSenderId: '71104364512',
    projectId: 'flutter-cloud-computing-tasks',
    databaseURL: 'https://flutter-cloud-computing-tasks-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-computing-tasks.firebasestorage.app',
    iosBundleId: 'com.example.ccSa1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCDw4Fh6dPmNt7AYPJy25vWJImuhrKWqI',
    appId: '1:71104364512:web:068831fc4fd5cc649df585',
    messagingSenderId: '71104364512',
    projectId: 'flutter-cloud-computing-tasks',
    authDomain: 'flutter-cloud-computing-tasks.firebaseapp.com',
    databaseURL: 'https://flutter-cloud-computing-tasks-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-computing-tasks.firebasestorage.app',
    measurementId: 'G-LKJLDZJNXS',
  );
}
